// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYh0W54URltjqNaZ6oC4g9A6KgcMB55t4',
    appId: '1:176648136526:web:fd69f7c4f1d3b63c24e01f',
    messagingSenderId: '176648136526',
    projectId: 'moviecatalog-3c9a5',
    authDomain: 'moviecatalog-3c9a5.firebaseapp.com',
    storageBucket: 'moviecatalog-3c9a5.firebasestorage.app',
    measurementId: 'G-7871VVFNWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1CS2W3DPa_5901PYcncM-zruQqcgqL-A',
    appId: '1:176648136526:android:ab36ee50bc64d1a224e01f',
    messagingSenderId: '176648136526',
    projectId: 'moviecatalog-3c9a5',
    storageBucket: 'moviecatalog-3c9a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9ugCUPoMFnHfuWIgS9TNF8aL90A1ZuM',
    appId: '1:176648136526:ios:fe9748cafe279e5824e01f',
    messagingSenderId: '176648136526',
    projectId: 'moviecatalog-3c9a5',
    storageBucket: 'moviecatalog-3c9a5.firebasestorage.app',
    iosBundleId: 'com.example.movieCatalogFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9ugCUPoMFnHfuWIgS9TNF8aL90A1ZuM',
    appId: '1:176648136526:ios:fe9748cafe279e5824e01f',
    messagingSenderId: '176648136526',
    projectId: 'moviecatalog-3c9a5',
    storageBucket: 'moviecatalog-3c9a5.firebasestorage.app',
    iosBundleId: 'com.example.movieCatalogFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYh0W54URltjqNaZ6oC4g9A6KgcMB55t4',
    appId: '1:176648136526:web:a32b68b567eede6924e01f',
    messagingSenderId: '176648136526',
    projectId: 'moviecatalog-3c9a5',
    authDomain: 'moviecatalog-3c9a5.firebaseapp.com',
    storageBucket: 'moviecatalog-3c9a5.firebasestorage.app',
    measurementId: 'G-779NP7KT9Q',
  );

}